//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectInvoice.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectInvoiceEntities : DbContext
    {
        public ProjectInvoiceEntities()
            : base("name=ProjectInvoiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Commodity> Commodities { get; set; }
        public virtual DbSet<ForeignCompany> ForeignCompanies { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<OurCompany> OurCompanies { get; set; }
    }
}
