//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectInvoice.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Commodity = new HashSet<Commodity>();
        }
    
        public int InvoiceID { get; set; }
        public int CompanyID { get; set; }
        public int ForeignCompanyID { get; set; }
        public string NoInvoice { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FinishDateDelivery { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentWay { get; set; }
        public Nullable<bool> IsPay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commodity> Commodity { get; set; }
        public virtual ForeignCompany ForeignCompany { get; set; }
        public virtual OurCompany OurCompany { get; set; }
    }
}
